### ISSUE TITLE
README: files-find-used-content

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/files-find-used-content#3]
Please get the new README.md from the [Child Template](https://github.com/byuitechops/child-template/blob/master/README.md) and fill it out for your child module. Push it to your child module's repository. 

If you have questions, ask Zach, Daniel, or Josh.

**Comment by maeashley** [comment]
My latest commit closes this issue. See [the commit](https://github.com/byuitechops/files-find-used-content/commit/03d531426451f91d29a7f3b3b1b0f9d23edfce52) for details.
